// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDikgVhr4GcROin_Yi2i6U3sizL9Igz3lw',
    appId: '1:861831268733:web:1165f44dd6d00ab2356414',
    messagingSenderId: '861831268733',
    projectId: 'wastenot-org',
    authDomain: 'wastenot-org.firebaseapp.com',
    storageBucket: 'wastenot-org.appspot.com',
    measurementId: 'G-E6QM9TKW0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFr3x152nAhstsp2EQo8Rel6zGRVclYtA',
    appId: '1:861831268733:android:1e71057f34d47362356414',
    messagingSenderId: '861831268733',
    projectId: 'wastenot-org',
    storageBucket: 'wastenot-org.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkmp1qZlhEZO2cnBLrK3Xydmv21qXn7xI',
    appId: '1:861831268733:ios:f3949fc5c7b4418a356414',
    messagingSenderId: '861831268733',
    projectId: 'wastenot-org',
    storageBucket: 'wastenot-org.appspot.com',
    iosClientId: '861831268733-grpj7tf1fal29amcii0env5ouua88ihc.apps.googleusercontent.com',
    iosBundleId: 'com.example.wastenot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkmp1qZlhEZO2cnBLrK3Xydmv21qXn7xI',
    appId: '1:861831268733:ios:f3949fc5c7b4418a356414',
    messagingSenderId: '861831268733',
    projectId: 'wastenot-org',
    storageBucket: 'wastenot-org.appspot.com',
    iosClientId: '861831268733-grpj7tf1fal29amcii0env5ouua88ihc.apps.googleusercontent.com',
    iosBundleId: 'com.example.wastenot',
  );
}
